calibration:
  calibration_wavelengths_file: wavelengths_2025-04-23.npy
  filter_cube_file: spectral_filter_ideal_2025-04-23.npy
  folder_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Calibration_data
  psf_name: ../Figure_Notebooks/sim_data_ideal_offset/blur/psf.npy
data:
  datafolder: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Figure_Notebooks/sim_data_ideal_offset/blur
  sample: blur
measurement_processing:
  bits: 16
  crop_indices:
  - 0
  - 600
  - 0
  - 600
  downsample_factor: 1
  wvmax: 890
  wvmin: 388
  wvstep: 8
reconstruction:
  kmax: 4000
  lamtv: 0
  rank: 4
  step_size: 0.01
  thr: 0.1
  xytv: 0.005
  use_low_rank: true
  use_one_hot: true
  temperature_decay: 0.995
  temperature_delay: 1000
  random_init: true
  temperature_init: 100
wandb:
  kprint: 100
  project_name: HyperSpectralDiffuserScope
  run_name: blur
  save_frequency: 1000000.0
  save_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Figure_Notebooks/sim_data_ideal_offset/blur
