calibration:
  calibration_wavelengths_file: wavelengths_2024-02-23.npy
  filter_cube_file: spectral_filter_2024-02-23.npy
  folder_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Calibration_data
  psf_name: ../Figure_Notebooks/sim_data/delta/psf.npy
data:
  datafolder: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Figure_Notebooks/sim_data/delta
  sample: delta
measurement_processing:
  bits: 16
  crop_indices:
  - 600
  - 1200
  - 1400
  - 2000
  downsample_factor: 1
  wvmax: 800
  wvmin: 450
  wvstep: 6
reconstruction:
  kmax: 2000
  lamtv: 0
  rank: 4
  step_size: 0.005
  thr: 0
  xytv: 2.0e-3
  use_low_rank: true
  use_one_hot: true
  temperature_decay: 0.999
  random_init: true
wandb:
  kprint: 100
  project_name: HyperSpectralDiffuserScope
  run_name: delta
  save_frequency: 1000000.0
  save_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/PlottingCode/Figure_Notebooks/sim_data/delta
