calibration:
  calibration_wavelengths_file: wavelengths_2024-02-23.npy
  filter_cube_file: spectral_filter_2024-02-23.npy
  folder_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/recon_materials_organized
  psf_name: psf_2024-05-23.npy
data:
  datafolder: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/DATA/SDCData/2024-05-31/code8eusmdy_10x
  sample: code8eusmdy_10x
measurement_processing:
  bits: 16
  crop_indices:
  - 420
  - 1852
  - 1150
  - 2626
  downsample_factor: 1
  wvmax: 800
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 601
  lamtv: .002
  rank: 1
  step_size: 0.05
  thr: .0005
  use_low_rank: true
  use_one_hot: true
  temperature_decay: 0.999
  temperature_delay: 300
  random_init: true
  xytv: 2.0e-4
wandb:
  kprint: 50
  project_name: FinalPaperRecons
  run_name: mrbles_d_paper
  save_frequency: 1000000.0
  save_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/Results