calibration:
  calibration_wavelengths_file: wavelengths_2024-02-23.npy
  filter_cube_file: spectral_filter_2024-02-23.npy
  folder_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/recon_materials_organized
  psf_name: psf_2024-05-23.npy
data:
  datafolder: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/DATA/SDCData/2024-05-30/code2sm_10x_2
  sample: code2sm_10x
measurement_processing:
  bits: 16
  crop_indices:
  - 420
  - 1852
  - 1350
  - 2826
  downsample_factor: 1
  wvmax: 800
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 601
  lamtv: .002
  rank: 1
  step_size: 0.05
  thr: .0005
  use_low_rank: true
  use_one_hot: true
  temperature_decay: 0.999
  xytv: 5.0e-4
  random_init: true
  temperature_delay: 300
wandb:
  kprint: 50
  project_name: FinalPaperRecons
  run_name: mrbles_c_paper
  save_frequency: 100.0
  save_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/Results
