calibration:
  calibration_wavelengths_file: wavelengths_2024-02-28.npy
  filter_cube_file: spectral_filter_2024-02-28.npy
  folder_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/JaxCode/Calibration_data
  psf_name: psf_2024-05-23.pt
data:
  datafolder: /home/neerja/DATA/SDCData/2024-05-31/code8eusmdy_10x
  sample: code8eusmdy_10x
measurement_processing:
  bits: 16
  crop_indices:
  - 420
  - 1852
  - 1150
  - 2626
  downsample_factor: 2
  wvmax: 700
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 2000
  lamtv: 0
  rank: 3
  step_size: 0.1
  thr: 6.0e-06
  use_low_rank: true
  use_one_hot: true
  xytv: 5.0e-06
wandb:
  kprint: 100
  project_name: New_Test
  run_name: one_hot_test
  save_frequency: 500
  save_location: test_models/


