calibration:
  calibration_wavelengths_file: wavelengths_2024-02-23.npy
  filter_cube_file: spectral_filter_2024-02-23.npy
  folder_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/recon_materials_organized
  psf_name: psf_2024-01-30.npy
data:
  datafolder: /media/azuldata/neerja/2024-02-01/mrbles_code3dy
  sample: code3dy_10x_berkeley
measurement_processing:
  bits: 16
  crop_indices:
    - 600
    - 1600
    - 1400
    - 2400
  downsample_factor: 1
  wvmax: 800
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 301
  lamtv: .002
  rank: 1
  step_size: 0.05
  thr: .0005
  use_low_rank: true
  use_one_hot: true
  temperature_decay: 0.999
  xytv: 2.0e-4
wandb:
  kprint: 50
  project_name: FinalPaperRecons
  run_name: mrbles_b_paper
  save_frequency: 1000000.0
  save_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/Results
