calibration:
  calibration_wavelengths_file: wavelengths_2024-02-28.npy
  filter_cube_file: spectral_filter_2024-02-28.npy
  folder_location: /home/emarkley/Workspace/PYTHON/HyperSpectralDiffuserScope/recon_materials_organized
  psf_name: psf_2024-01-30.npy
data:
  datafolder: /media/azuldata/neerja/2024-04-22_huvec_patterned/huvec_CAL_10x
  sample: 2024-04-22_huvec_patterned
measurement_processing:
  bits: 16
  crop_indices:
  - 420
  - 1852
  - 1250
  - 2626
  downsample_factor: 1
  wvmax: 700
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 1000
  lamtv: 3.0
  rank: 3
  step_size: 0.1
  thr: 0.0001
  use_low_rank: true
  use_one_hot: true
  xytv: 5.0e-07
wandb:
  kprint: 50
  project_name: FinalPaperRecons
  run_name: Huvec_CAL_lamtv_1.0_thr_0.0001_step_1.0_xytv_5e-06
  save_frequency: 1000000.0
  save_location: /home/emarkley/Workspace/PYTHON/spectraldiffuserscope/Results