calibration:
  calibration_wavelengths_file: wavelengths_2024-02-28.npy
  filter_cube_file: spectral_filter_2024-02-28.npy
  folder_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/JaxCode/Calibration_data
  psf_name: psf_2024-01-30.pt
data:
  datafolder: /media/azuldata/neerja/2024-02-01/drying_beads_drop/meas0022
  sample: drying_beads_drop
measurement_processing:
  bits: 16
  crop_indices:
  - 420
  - 1852
  - 1450
  - 2826
  downsample_factor: 1
  wvmax: 700
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 1000
  lamtv: 2.0e-06
  rank: 3
  step_size: 0.25
  thr: 0.0006
  use_low_rank: false
  use_one_hot: true
  xytv: 0
wandb:
  kprint: 100
  project_name: HyperSpectralDiffuserScope
  run_name: dryingbeadsdrop_0022
  save_frequency: 1000000.0
  save_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/JaxCode/Results
