calibration:
  calibration_wavelengths_file: wavelengths_2024-02-28.npy
  filter_cube_file: spectral_filter_2024-02-28.npy
  folder_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/JaxCode/Calibration_data
  psf_name: psf_2024-04-22.pt
data:
  datafolder: /media/azuldata/neerja/2024-04-22_huvec_patterned/fluoro_beads
  sample: fluoro_beads
measurement_processing:
  bits: 16
  crop_indices:
  - 620
  - 1652
  - 1350
  - 2326
  downsample_factor: 1
  wvmax: 700
  wvmin: 450
  wvstep: 8
reconstruction:
  kmax: 1000
  lamtv: 2.0e-06
  rank: 3
  step_size: 0.025
  thr: 6.0e-04
  use_low_rank: true
  use_one_hot: false
  xytv: 0 #1.0e-06
wandb:
  kprint: 100
  project_name: HyperSpectralDiffuserScope
  run_name: fluoro_beads_LRH1k_Feb28spectralCal_noDownSample_step0.025_thr6e-04_lam2e-06
  save_frequency: 1000000.0
  save_location: /home/neerja/CODE/SpectralDiffuserScopeGitRepo/JaxCode/Results
