wandb_version: 1

wvmin:
  desc: null
  value: 450
wvmax:
  desc: null
  value: 800
wvstep:
  desc: null
  value: 6
kmax:
  desc: null
  value: 2000
step_size:
  desc: null
  value: 0.1
thr:
  desc: null
  value: 6.0e-06
xytv:
  desc: null
  value: 1.0e-06
lamtv:
  desc: null
  value: 2.0e-06
kprint:
  desc: null
  value: 100
dict_learn:
  desc: null
  value: false
downsample_factor:
  desc: null
  value: 2
sample:
  desc: null
  value: mrbles_code3dy
gpu:
  desc: null
  value: 0
spectral_calibration:
  desc: null
  value: Calibration_data/spectral_calibration_2024-02-23_8nmFWHM.pt
psf:
  desc: null
  value: recon_materials_organized/psf_2024-01-30.pt
power:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710373405.753177
    t:
      1:
      - 1
      - 12
      - 41
      - 45
      - 55
      2:
      - 1
      - 12
      - 41
      - 45
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
